# Copyright 2019 Yoshiya Hinosawa. All rights reserved. Blue Oak license.
name: License Checker
description: GitHub Action for checking the license lines of the files in a repository
author: Yoshiya Hinosawa <stibium121@gmail.com>
branding:
  icon: align-left
  color: purple
inputs: {}
outputs: {}
runs:
  using: docker
  image: Dockerfile
