# Copyright 2019 Yoshiya Hinosawa. All rights reserved. Blue Oak license.
name: License Checker
author: Yoshiya Hinosawa <stibium121@gmail.com>
inputs: {}
outputs: {}
runs:
  using: docker
  image: Dockerfile
